<a href="https://colab.research.google.com/github/shivamshinde70/dsbda/blob/main/As_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("E:\heartdisease.csv")

In [ ]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [ ]:
df1=df.groupby('Age')['Slope'].mean()

In [ ]:
df1

Age
29    1.000000
34    1.000000
35    1.250000
37    2.000000
38    1.500000
39    1.500000
40    1.333333
41    1.200000
42    1.625000
43    1.625000
44    1.363636
45    1.750000
46    1.714286
47    1.200000
48    1.571429
49    1.400000
50    1.571429
51    1.333333
52    1.307692
53    1.750000
54    1.562500
55    1.875000
56    2.090909
57    1.588235
58    1.631579
59    1.714286
60    1.500000
61    1.625000
62    2.000000
63    1.666667
64    1.800000
65    1.375000
66    1.857143
67    1.777778
68    1.750000
69    1.666667
70    2.000000
71    1.333333
74    1.000000
76    2.000000
77    1.000000
Name: Slope, dtype: float64

In [ ]:
mean_Slope=df1.rename("meanSlope").reset_index()

In [ ]:
mean_Slope

    Age  meanSlope
0    29   1.000000
1    34   1.000000
2    35   1.250000
3    37   2.000000
4    38   1.500000
5    39   1.500000
6    40   1.333333
7    41   1.200000
8    42   1.625000
9    43   1.625000
10   44   1.363636
11   45   1.750000
12   46   1.714286
13   47   1.200000
14   48   1.571429
15   49   1.400000
16   50   1.571429
17   51   1.333333
18   52   1.307692
19   53   1.750000
20   54   1.562500
21   55   1.875000
22   56   2.090909
23   57   1.588235
24   58   1.631579
25   59   1.714286
26   60   1.500000
27   61   1.625000
28   62   2.000000
29   63   1.666667
30   64   1.800000
31   65   1.375000
32   66   1.857143
33   67   1.777778
34   68   1.750000
35   69   1.666667
36   70   2.000000
37   71   1.333333
38   74   1.000000
39   76   2.000000
40   77   1.000000

In [ ]:
df2=df.merge(mean_Slope)

In [ ]:
df2

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD,meanSlope
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No,1.666667
1,9,63,1,asymptomatic,130,254,0,2,147,0,1.4,2,1.0,reversable,Yes,1.666667
2,95,63,0,nonanginal,135,252,0,2,172,0,0.0,1,0.0,normal,No,1.666667
3,119,63,1,asymptomatic,130,330,1,2,132,1,1.8,1,3.0,reversable,Yes,1.666667
4,122,63,0,asymptomatic,150,407,0,2,154,0,4.0,2,3.0,reversable,Yes,1.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,162,77,1,asymptomatic,125,304,0,2,162,1,0.0,1,3.0,normal,Yes,1.000000
299,212,38,1,typical,120,231,0,0,182,1,3.8,2,0.0,reversable,Yes,1.500000
300,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No,1.500000
301,234,74,0,nontypical,120,269,0,2,121,1,0.2,1,1.0,normal,No,1.000000
302,258,76,0,nonanginal,140,197,0,1,116,0,1.1,2,0.0,normal,No,2.000000

In [ ]:
stacked=df.stack()

In [ ]:
stacked

0    Unnamed: 0          1
     Age                63
     Sex                 1
     ChestPain     typical
     RestBP            145
                    ...
302  ExAng               0
     Oldpeak           0.0
     Slope               1
     Thal           normal
     AHD                No
Length: 4539, dtype: object

In [ ]:
stacked.unstack()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [ ]:
df3=df.T

In [ ]:
df3

,0,1,2,3,4,5,6,7,8,9,...,293,294,295,296,297,298,299,300,301,302
Unnamed: 0,1,2,3,4,5,6,7,8,9,10,...,294,295,296,297,298,299,300,301,302,303
Age,63,67,67,37,41,56,62,57,63,53,...,63,63,41,59,57,45,68,57,57,38
Sex,1,1,1,1,0,1,0,0,1,1,...,1,0,1,1,0,1,1,1,0,1
ChestPain,typical,asymptomatic,asymptomatic,nonanginal,nontypical,nontypical,asymptomatic,asymptomatic,asymptomatic,asymptomatic,...,asymptomatic,asymptomatic,nontypical,asymptomatic,asymptomatic,typical,asymptomatic,asymptomatic,nontypical,nonanginal
RestBP,145,160,120,130,130,120,140,120,130,140,...,140,124,120,164,140,110,144,130,130,138
Chol,233,286,229,250,204,236,268,354,254,203,...,187,197,157,176,241,264,193,131,236,175
Fbs,1,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
RestECG,2,2,2,0,2,0,2,0,2,2,...,2,0,0,2,0,0,0,0,2,0
MaxHR,150,108,129,187,172,178,160,163,147,155,...,144,136,182,90,123,132,141,115,174,173
ExAng,0,1,1,0,0,0,0,1,0,1,...,1,1,0,0,1,0,0,1,0,0
Oldpeak,2.3,1.5,2.6,3.5,1.4,0.8,3.6,0.6,1.4,3.1,...,4.0,0.0,0.0,1.0,0.2,1.2,3.4,1.2,0.0,0.0
Slope,3,2,2,3,1,1,3,1,2,3,...,1,2,1,2,2,2,2,2,2,1
Ca,0.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,...,2.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,1.0,NaN
Thal,fixed,normal,reversable,normal,normal,normal,normal,normal,reversable,reversable,...,reversable,normal,normal,fixed,reversable,reversable,reversable,reversable,normal,normal
AHD,No,Yes,Yes,No,No,No,Yes,No,Yes,Yes,...,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No

In [ ]:
df.dropna()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [ ]:
df.fillna('nodata')

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [ ]:
df.fillna('6',inplace=True)

In [ ]:
x=df["Age"].mean()

In [ ]:
x

54.54208754208754

In [ ]:
x=df["Age"].median()

In [ ]:
x

56.0

In [ ]:
x=df["Age"].mode()

In [ ]:
x

0    58
dtype: int64

In [ ]:
df.loc[2,'Age']=45

In [ ]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,45,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [ ]:
for x in df.index:
    if df.loc[x,"Age"]>60:
        df.loc[x,"Age"]=60

In [ ]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,60,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,60,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,45,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,60,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [ ]:
for x in df.index:
    if df.loc[x,"Age"]>60:
        df.drop(x,inplace=True)

In [ ]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,60,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,60,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,45,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,60,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes

In [ ]:
print(df.duplicated())
df.drop_duplicates(inplace=True)

0      False
1      False
2      False
3      False
4      False
       ...
297    False
298    False
299    False
300    False
301    False
Length: 297, dtype: bool

In [ ]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,60,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,60,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,45,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,298,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable,Yes
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,60,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes